name: launcher_flutter
description: Multi-platform launcher with drag, zoom, context menu and encrypted storage.
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.5.0
  shared_preferences: ^2.3.2
  encrypt: ^5.0.1
  http: ^1.2.2
  url_launcher: ^6.3.0
  file_picker: ^8.1.2
  image: ^4.1.3
  flutter_markdown: ^0.7.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true








